package com.team.landhouse.entities;

import java.util.Date;

public class ProjectModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ProjectId
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    private int projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Code
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Name
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Creator
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Created
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    private String created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Modifier
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Modified
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ProjectId
     *
     * @return the value of project.ProjectId
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public int getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ProjectId
     *
     * @param projectid the value for project.ProjectId
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public void setProjectid(int projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Code
     *
     * @return the value of project.Code
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Code
     *
     * @param code the value for project.Code
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Name
     *
     * @return the value of project.Name
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Name
     *
     * @param name the value for project.Name
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Creator
     *
     * @return the value of project.Creator
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Creator
     *
     * @param creator the value for project.Creator
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Created
     *
     * @return the value of project.Created
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Created
     *
     * @param created the value for project.Created
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public void setCreated(String created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Modifier
     *
     * @return the value of project.Modifier
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Modifier
     *
     * @param modifier the value for project.Modifier
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Modified
     *
     * @return the value of project.Modified
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Modified
     *
     * @param modified the value for project.Modified
     *
     * @mbggenerated Wed Apr 26 00:44:40 ICT 2017
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}